### PR TITLE
Move to subtree

### PR DESCRIPTION
**Pull request by aaronlippold**

### CODE REVIEW

**Comment by aaronlippold** [comment]
Note - I used the method here: https://stackoverflow.com/questions/28215244/convert-git-submodule-to-subtree

**Comment by sharmay** [comment]
subtree embeds it where as submodule only adds a reference
1.  Adding a reference is preferred to always get the latest from upstream
2. keep overall repo sized small

I suggest keep it as submodule.

**Review by jkatz — CHANGES_REQUESTED** [review]
Preference is to leave as submodule.

**Review by hunleyd — COMMENTED** [review]
i prefer submodule as well

**Comment by aaronlippold** [comment]
I agree with 1. Which is my actual intention. I always wanted to reference master. 

From my understanding submodules reference a point in time aka specific git commit and not a reference to the top of the head. I thought subtrees actually solved that issue and allowed you to truly reference the head of master without the need to maintain pulling in the new commits like you do with a sub module. I could be misunderstanding.

I understanding is this. With a sub module I commit a reference to a point in time of another repository in my repo, a specific get commit of that repo reference. If the reference repo receives more commits I actually have to update The other repository point the sub module to the new set of commits. Which means I have a maintenance tail for the repository that is referencing other repos to keep it in sync. I was trying to avoid this given that we always wanted whatever master was.

**Pull request closed without merging**
