### PR TITLE
removed the hugo sub-dir from the inspec profile

### PR DESCRIPTION
**Pull request by aaronlippold**
move it into a seperate branch

Signed-off-by: Aaron Lippold <lippold@gmail.com>

### CODE REVIEW

**Comment by sharmay** [comment]
@jkatz any opinion ?

**Review by jkatz — APPROVED** [review]

**Comment by sharmay** [comment]
@aaronlippold 
What issue we have when docs are kept in master branch ?
As a developer, it requires extra steps to keep docs updates.

**Review by hunleyd — COMMENTED** [review]
i would prefer not to have switch branches every time i need to tweak a doc

**Comment by aaronlippold** [comment]
Well shouldn't the doc's actually just be pulling the read me from the
repo? We should never actually have to update anything in the Hugo site.
Updates to the read me file should be done in the profile and the Hugo site
should be rebuilt whenever we pusha change to the read me in the profile.
Just my opinion.

**Comment by aaronlippold** [comment]
So if I'm understanding how we have things configured. That should be a commit hook in the profile repo that tells Hugo to rebuild itself on a change to the read me file. And The Hugo Branch should just pull the read me whenever it builds itself. Perhaps we don't even need to make it that complicated. If we just tell Hugo to always pull from the profile reading whenever we need to rebuild Hugo statically it should always be up-to-date with whatever's a master or at least up to date with whatever release is most current.

**Comment by aaronlippold** [comment]
Fundamentally having a Hugo website in the middle of an inspect profile isn't really supported or expected. The fact that the Hugo said uses data from the inspect profile is perfectly fine but not in no way connects the two

**Pull request closed without merging**
