### PR TITLE
Update V-72841.rb to have multiple cci and nist tags in an array inst…

### PR DESCRIPTION
**Pull request by steve-hetzel**
…ead of multiple tags.

### CODE REVIEW

**Review by sharmay — COMMENTED** [review]
nist tag, are they treated as pair ?
if so do we need array in array ?

**Review by aaronlippold — CHANGES_REQUESTED** [review]
We only need to have Rev_4 listed once in the arrays.

**Review by aaronlippold — APPROVED** [review]

**Comment by aaronlippold** [comment]
in theory they are a pair but really we have a flat data structure in this case and given we don't want to try to manage a data structure inside the controls. We are working with the inspec folks to build object support into the tags for better manageability. For now this seems to be the most direct path for managing the information in the controls.

**Comment by aaronlippold** [comment]
We also need to do this to all the other controls as well with multiple tags.

**Pull request merged**
